### ISSUE TITLE
AttributeError: PMS (Property Management System) 

### ISSUE THREAD

**Issue by novejsn** [OCA/pms#19]
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 185, in load_module_graph
    getattr(py_module, pre_init)(cr)
  File "/usr/local/lib/python3.7/dist-packages/odoo/addons/pms/init_hook.py", line 13, in pre_init_hook
    ResConfig.sudo().create(default_values).execute()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 623, in execute
    self.set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/website_sale_stock/models/res_config_settings.py", line 20, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/res_config_settings.py", line 67, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/purchase/models/res_config_settings.py", line 42, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/res_config_settings.py", line 144, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/models/res_config_settings.py", line 72, in set_values
    res = super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/project/models/res_config_settings.py", line 33, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/crm/models/res_config_settings.py", line 111, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/res_config_settings.py", line 111, in set_values
    super(ResConfigSettings, self).set_values()
  File "/mnt/addons/formio/models/res_config_settings.py", line 51, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/res_config_settings.py", line 71, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/local/lib/python3.7/dist-packages/odoo/addons/muk_web_theme/models/res_config_settings.py", line 73, in set_values
    res = super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/res_config_settings.py", line 35, in set_values
    super(ResConfigSettings, self).set_values()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 580, in set_values
    groups.write({'implied_ids': [(4, implied_group.id)]})
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/res_users.py", line 170, in write
    write_res = super(res_groups_mail_channel, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1133, in write
    res = super(GroupsView, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 1039, in write
    res = super(GroupsImplied, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_users.py", line 229, in write
    return super(Groups, self).write(vals)
  File "/usr/local/lib/python3.7/dist-packages/odoo/addons/multi_pms_properties/models.py", line 32, in write
    or (field.relational and field.check_pms_properties)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'Many2many' object has no attribute 'check_pms_properties'

**Comment by DarioLodeiros** [comment]
This module depends of pms_multiproperties, in the pms_multiproperties readme you can read the installation instructions: https://github.com/OCA/pms/tree/14.0/multi_pms_properties#installation

Anyway, this module is in alpha state and you can expect an unstable code at the moment

Thanks!
