### ISSUE TITLE
OCA PMS Module Activate Error: KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7fd632bd0d30>, 'web.assets_backend')

### ISSUE THREAD

**Issue by markstrefford** [OCA/pms#215]
Activation of PMS module is failing with 

`KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7fd632bd0d30>, 'web.assets_backend')`
 
## Module
PMS https://odoo-community.org/shop/pms-property-management-system-5626#attr=8864

## Describe the bug
I've installed Odoo v14 and the dependencies for the PMS module. When I try to activate it, I get the following error:

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo14/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/odoo/odoo14/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/odoo14/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7fd632bd0d30>, 'web.assets_backend')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 676, in _tag_template
    return self._tag_record(record)
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 568, in _tag_record
    f_val = self.id_get(f_ref, raise_if_not_found=nodeattr2bool(rec, 'forcecreate', True))
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 681, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 687, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/odoo/odoo14/odoo/odoo/addons/base/models/ir_model.py", line 2023, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-40>", line 2, in _xmlid_lookup
  File "/odoo/odoo14/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo14/odoo/odoo/addons/base/models/ir_model.py", line 2016, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.assets_backend

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo14/odoo/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/odoo14/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/odoo/odoo14/odoo/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/odoo14/odoo/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/odoo14/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/odoo14/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/odoo14/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo14/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo14/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo14/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-74>", line 2, in button_immediate_install
  File "/odoo/odoo14/odoo/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo14/odoo/odoo/addons/base/models/ir_module.py", line 491, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo14/odoo/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/odoo/odoo14/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/odoo14/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/odoo14/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo14/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo14/odoo/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/odoo14/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/odoo/odoo14/odoo/odoo/tools/convert.py", line 711, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing None:8, somewhere inside
<data name="queue.job.assets" inherit_id="web.assets_backend">
    <xpath expr="." position="inside">
      <link rel="stylesheet" href="/queue_job/static/lib/vis/vis-network.min.css"/>
      <link rel="stylesheet" type="text/scss" href="/queue_job/static/src/scss/queue_job_fields.scss"/>

      <script type="text/javascript" src="/queue_job/static/lib/vis/vis-network.min.js"/>
      <script type="text/javascript" src="/queue_job/static/src/js/queue_job_fields.js"/>
    </xpath>
  </data>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8069/web/assets/197-596cd2f/web.assets_backend.min.js:983:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/197-596cd2f/web.assets_backend.min.js:991:13)
```
## To Reproduce
**Affected versions**:

1. Install Odoo v14 on MacOS 13.4
2. Setup PostgreSQL DB (this works, Odoo starts and I can add modules, etc.)
3. Copy PMS and related modules into addons folder
4. Start Oddo with `python3 odoo-bin --addons-path=addons -d odoo14 --load multi_pms_properties`
5. Refresh the apps list
6. Activate the PMS module

**Expected behavior**
The PMS module is activated as per the instructions.

**Additional context**
Python 3.9 in a conda environment specifically setup for Odoo
Dependencies installed from Odoo14 requirements.txt

**Comment by DarioLodeiros** [comment]
Hello Mark

I'm sorry to tell you that I can't help you too much, the error that appears to you is not familiar to me with pms, it is a loss of reference error to an odoo core template, I intuit that it is a problem derived from the environment, but I can't give you many more clues.
Anyway, I would like to notify you of the beta status of the application, which means that it can receive changes and refactorings that destabilize a system in production.

Greetings

**Comment by DarioLodeiros** [comment]
I'm going to close the issue because I don't think it's related to development, if you discover anything related to a bug in the code feel free to create a new one.

Thank you!

**Comment by markstrefford** [comment]
That's a disappointing response. 

Could you give me details of an environment where this does work? For example, specifically what versions of Odoo and the dependent Odoo modules you have? What Python version? etc. etc. This information is not visible in the rather short and incomplete installation instructions.
