### ISSUE TITLE
Odoo 14 pms module - Error: Mixing apples and oranges in reservation creation

### ISSUE THREAD

**Issue by Johnrivera7** [OCA/pms#222]
After installing the pms (Property Management System) module in Odoo 14, I encountered an error while trying to create a reservation for testing purposes. The system raised a TypeError with the following traceback:
Traceback (most recent call last):
  File "/odoo_versalles/odoo_versalles-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo_versalles/odoo_versalles-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo_versalles/odoo_versalles-server/odoo/http.py", line 370, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo_versalles/odoo_versalles-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo_versalles/odoo_versalles-server/odoo/http.py", line 358, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo_versalles/odoo_versalles-server/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/odoo_versalles/odoo_versalles-server/odoo/http.py", line 544, in response_wrap
    response = f(*args, **kw)
  File "/odoo_versalles/odoo_versalles-server/addons/web/controllers/main.py", line 1370, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo_versalles/odoo_versalles-server/addons/web/controllers/main.py", line 1362, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo_versalles/odoo_versalles-server/odoo/api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo_versalles/odoo_versalles-server/odoo/api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo_versalles/odoo_versalles-server/addons/web/models/models.py", line 568, in search_panel_select_range
    comodel_records = Comodel.search_read(comodel_domain, field_names, limit=limit)
  File "/odoo_versalles/odoo_versalles-server/odoo/models.py", line 4855, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo_versalles/odoo_versalles-server/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo_versalles/odoo_versalles-server/odoo/models.py", line 4524, in _search
    query = self._where_calc(args)
  File "/odoo_versalles/odoo_versalles-server/odoo/models.py", line 4280, in _where_calc
    return expression.expression(domain, self).query
  File "/odoo_versalles/odoo_versalles-server/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/odoo_versalles/odoo_versalles-server/odoo/osv/expression.py", line 668, in parse
    dom = HIERARCHY_FUNCS[operator](left, ids2, model)
  File "/odoo_versalles/odoo_versalles-server/odoo/osv/expression.py", line 576, in parent_of_domain
    records = records[parent_name] - records.browse(parent_ids)
  File "/odoo_versalles/odoo_versalles-server/odoo/models.py", line 5606, in __sub__
    raise TypeError("Mixing apples and oranges: %s - %s" % (self, other))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo_versalles/odoo_versalles-server/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo_versalles/odoo_versalles-server/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: Mixing apples and oranges: res.partner() - pms.property(1,)

**Comment by Johnrivera7** [comment]
please help @DarioLodeiros

**Comment by DarioLodeiros** [comment]
we are fixing the problem, provisionally you can comment the lines inside the searchpanel section of the search views that have the pms_property_id field (for example in folio: https://github.com/OCA/pms/blob/14.0/pms/views /pms_folio_views.xml#L820, same in pms_reservation_views and pms_checkin_views)

**Comment by Johnrivera7** [comment]
Thank you very much, commenting on the lines that you indicate I was able to solve the error, in which I can collaborate, the translations into Spanish are not correct

**Comment by Johnrivera7** [comment]
> we are fixing the problem, provisionally you can comment the lines inside the searchpanel section of the search views that have the pms_property_id field (for example in folio: https://github.com/OCA/pms/blob/14.0/pms/views /pms_folio_views.xml#L820, same in pms_reservation_views and pms_checkin_views)

Thank you very much, commenting on the lines that you indicate I was able to solve the error, in which I can collaborate, the translations into Spanish are not correct

**Comment by remytms** [comment]
The error occurs after the publication of this commit in odoo 14.0: https://github.com/odoo/odoo/commit/3c9b3457086
